all:
	@echo Please use one of the following..
#	@echo make -fmakefile.dos	For DJGPP
	@echo make -fmakefile.lin	For Linux
#	@echo make -fmakefile.be	For BeOS R4 for intel
#	@echo make -fmakefile.win	For Windows 95 with MING or Cygnus

